output "region" {
  description = "AWS region"
  value       = var.region
}

output "cluster_name" {
  description = "EKS cluster name"
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks.cluster_endpoint
}

output "kubeconfig_filename" {
  description = "kubectl config filename generated by EKS module"
  value       = module.eks.kubeconfig_filename
}

# output "eks_role_arn" {
#   description = "Role ARN to create/access EKS cluster"
#   value       = module.identity.eks_role_arn
# }