---
image: gcr.io/prysmaticlabs/prysm/beacon-chain
imageTag: latest

replicas: 1

containerArgs:
  - "--config-file"
  - "/data/config/beacon-client.yaml"

config:
  datadir: ./data
  p2p-host-ip: 
  p2p-tcp-port: 13000
  log-file: /data/beacon.log
  verbosity:

storage:
  capacity: "20Gi"

resources:
  limits:
    memory: "8Gi"
  requests:
    memory: "4Gi"