apiVersion: v1
kind: PersistentVolume
metadata:
  name: beacon-data
  labels:
    type: local
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.storage.capacity | quote }}
  hostPath:
    path: /data